export default [
  {
    driverName: "Patrick",
    startingPoint: "Opéra, Paris",
    pointOfArrival: "Place de france, Massy",
    price: 13.5,
    formula: "Comfort",
    nbOfPassenger: 3,
    droppedOffTime: "14h53",
    date: "Vendredi 15 mars",
    status: "Done",
  },
  {
    driverName: "Vincent",
    startingPoint: "rue vert, Longjumeau",
    pointOfArrival: "rue orange, Villebon",
    price: 103.95,
    formula: "VIP",
    nbOfPassenger: 3,
    droppedOffTime: "10h56",
    date: "Jeudi 9 juin",
    status: "Cancelled",
  },
  //le bon
  {
    driverName: "Anna",
    departure: "rue gris, Montpellier",
    arrival: "Rue bordeau, Nantes",
    price: 93.35,
    distance: 809,
    formula: "Taxi",
    nbOfPassenger: 5,
    droppedOffTime: "02h11",
    date: "Lundi 2 mai",
    status: "Pending",
  },
];
